### ISSUE TITLE
fix: 図3.1 プロファイラ―モジュール一覧

### ISSUE THREAD

**Issue by 2RiniaR** [CyberAgentGameEntertainment/UnityPerformanceTuningBible#18]
素晴らしい参考書を共有していただきありがとうございます。
読み進めている際に誤りを発見したため、ソースと修正案を記述させていただきます。

▼対象
（画像）図3.1 プロファイラ―モジュール一覧

▼詳細
- Global Illuminationに対応する説明が、UI Detailsのものになっています。
- Virtual Texturingに対応する説明が、Global Illuminationのものになっています。
- Virtual Texturingに対応する説明がありません。

▼ソース
https://docs.unity3d.com/2020.3/Documentation/Manual/ProfilerWindow.html

▼修正案
![profiler_module_list_after](https://user-images.githubusercontent.com/45062199/206651638-297a4911-bc79-4dcd-9f85-4bfd34120cfe.png)
赤字の部分が修正箇所です。
表に使用されているスタイルやフォントが確認できなかったため、修正案の提示という形にさせていただきました。

よろしくお願いいたします。

**Comment by iida-takuya-ca** [comment]
丁寧にありがとうございます。
こちら対応します。

**Comment by iida-takuya-ca** [comment]
@2RiniaR 
こちら先ほどマージ致しました。
ご報告ありがとうございました。
(画像で制作しておりPR出しにくい構造で申し訳ないです)

**Comment by 2RiniaR** [comment]
@iida-takuya-ca 
対応していただき、ありがとうございました。
当書籍は非常に参考になっているため、少しでもお役に立てたのであれば幸いです。
