### ISSUE TITLE
English Version for UnityPerformanceTuningBible.pdf

### ISSUE THREAD

**Issue by kkkarannn** [CyberAgentGameEntertainment/UnityPerformanceTuningBible#9]
It would be great to have an English version of the pdf for the international audience.
Thank you.

**Comment by iida-takuya-ca** [comment]
Sorry for the delay in responding.

We were considering whether we could translate from PDF using "GCP Document Translation" or "DeepL".
We actually translated it, but the quality was not up to the level we could show you, so we would appreciate it if you could translate it for us.

An easy way to translate the full text is to use the "XXX.re" file placed in "[article/text](https://github.com/CyberAgentGameEntertainment/UnityPerformanceTuningBible/tree/main/articles/text)" as the original text.
I think it would be easier to run this through a translator and read it.

We will continue to consider using these services if we can improve the accuracy of the translation!

**Comment by iida-takuya-ca** [comment]
We try to translate this book by DeepL.

First we tried to translate it by original pdf to translated pdf.
However the  result was not readable.

Second we tried to tranlate it by original text to translated text.
It is much easier to read, although there are some odd sentence due to the ReView format.

So We're fine-tuning now.
We will be able to release it soon.

**Comment by iida-takuya-ca** [comment]
We have just released the English version!
You can download it from [the latest version of Releases](https://github.com/CyberAgentGameEntertainment/UnityPerformanceTuningBible/releases/latest).

We have also summarized the process for translating into other languages in [README_EN](https://github.com/CyberAgentGameEntertainment/UnityPerformanceTuningBible/blob/main/README_EN.md)
Please take a look if you are interested.

Furthermore, we have documented the process of this release in [our company's blog](https://developers.cyberagent.co.jp/blog/archives/41291/).
Please feel free to check it out if you are interested.
